"""migration

Revision ID: b8e8c570ad43
Revises: 
Create Date: 2026-08-13 10:57:47.926821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e8c570ad43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_router',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchanges',
    sa.Column('mic', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mic')
    )
    op.create_table('symbols_universe',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('universe_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_traded', sa.Date(), nullable=False),
    sa.Column('auto_close_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_traded', sa.Date(), nullable=False),
    sa.Column('auto_close_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('declared_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_payouts_asset_id'), 'dividend_payouts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dividend_payouts_ex_date'), 'dividend_payouts', ['ex_date'], unique=False)
    op.create_table('equities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_traded', sa.Date(), nullable=False),
    sa.Column('auto_close_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_assets',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('mic', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_traded', sa.Date(), nullable=False),
    sa.Column('auto_close_date', sa.Date(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.ForeignKeyConstraint(['mic'], ['exchanges.mic'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_exchange_assets_asset_id'), 'exchange_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_exchange_assets_mic'), 'exchange_assets', ['mic'], unique=False)
    op.create_index(op.f('ix_exchange_assets_quote_id'), 'exchange_assets', ['quote_id'], unique=False)
    op.create_table('mergers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mergers_asset_id'), 'mergers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_mergers_effective_date'), 'mergers', ['effective_date'], unique=False)
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_splits_asset_id'), 'splits', ['asset_id'], unique=False)
    op.create_index(op.f('ix_splits_effective_date'), 'splits', ['effective_date'], unique=False)
    op.create_table('stock_dividend_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('declared_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('payment_sid', sa.String(), nullable=False),
    sa.Column('ration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_dividend_payouts_asset_id'), 'stock_dividend_payouts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_stock_dividend_payouts_ex_date'), 'stock_dividend_payouts', ['ex_date'], unique=False)
    op.create_table('symbols_universe_assets',
    sa.Column('symbol_universe_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_router.id'], ),
    sa.ForeignKeyConstraint(['symbol_universe_name'], ['symbols_universe.name'], ),
    sa.PrimaryKeyConstraint('symbol_universe_name', 'start_date', 'asset_id')
    )
    op.create_table('futures_contracts',
    sa.Column('root_asset_id', sa.Integer(), nullable=False),
    sa.Column('root_exchange_asset_sid', sa.Integer(), nullable=True),
    sa.Column('notice_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_traded', sa.Date(), nullable=False),
    sa.Column('auto_close_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset_router.id'], ),
    sa.ForeignKeyConstraint(['root_asset_id'], ['asset_router.id'], ),
    sa.ForeignKeyConstraint(['root_exchange_asset_sid'], ['exchange_assets.sid'], ),
    sa.PrimaryKeyConstraint('root_asset_id', 'id')
    )
    op.create_index(op.f('ix_futures_contracts_root_exchange_asset_sid'), 'futures_contracts', ['root_exchange_asset_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_futures_contracts_root_exchange_asset_sid'), table_name='futures_contracts')
    op.drop_table('futures_contracts')
    op.drop_table('symbols_universe_assets')
    op.drop_index(op.f('ix_stock_dividend_payouts_ex_date'), table_name='stock_dividend_payouts')
    op.drop_index(op.f('ix_stock_dividend_payouts_asset_id'), table_name='stock_dividend_payouts')
    op.drop_table('stock_dividend_payouts')
    op.drop_index(op.f('ix_splits_effective_date'), table_name='splits')
    op.drop_index(op.f('ix_splits_asset_id'), table_name='splits')
    op.drop_table('splits')
    op.drop_index(op.f('ix_mergers_effective_date'), table_name='mergers')
    op.drop_index(op.f('ix_mergers_asset_id'), table_name='mergers')
    op.drop_table('mergers')
    op.drop_index(op.f('ix_exchange_assets_quote_id'), table_name='exchange_assets')
    op.drop_index(op.f('ix_exchange_assets_mic'), table_name='exchange_assets')
    op.drop_index(op.f('ix_exchange_assets_asset_id'), table_name='exchange_assets')
    op.drop_table('exchange_assets')
    op.drop_table('equities')
    op.drop_index(op.f('ix_dividend_payouts_ex_date'), table_name='dividend_payouts')
    op.drop_index(op.f('ix_dividend_payouts_asset_id'), table_name='dividend_payouts')
    op.drop_table('dividend_payouts')
    op.drop_table('currencies')
    op.drop_table('commodities')
    op.drop_table('symbols_universe')
    op.drop_table('exchanges')
    op.drop_table('asset_router')
    # ### end Alembic commands ###
