import datetime
from typing import Any, Self

import pandas as pd
import polars as pl
import aiocache
from aiocache import Cache

from ziplime.assets.domain.asset_type import AssetType
from ziplime.assets.entities.asset import Asset
from ziplime.assets.entities.asset_symbol import AssetSymbol
from ziplime.assets.entities.bond import Bond
from ziplime.assets.entities.bond_event import BondEvent
from ziplime.assets.entities.dividend_payout import DividendPayout
from ziplime.assets.entities.exchange_asset import ExchangeAsset
from ziplime.assets.entities.exchange_info import ExchangeInfo
from ziplime.assets.entities.split import Split
from ziplime.assets.entities.symbol_universe import SymbolsUniverse
from ziplime.assets.models.asset_router import AssetRouter
from ziplime.assets.entities.commodity import Commodity
from ziplime.assets.entities.currency import Currency
from ziplime.assets.entities.equity import Equity
from ziplime.assets.entities.futures_contract import FuturesContract
from ziplime.assets.entities.futures_root import FuturesRoot
from ziplime.assets.models.currency_model import CurrencyModel
from ziplime.assets.models.equity_model import EquityModel
from ziplime.assets.models.futures_contract_model import FuturesContractModel
from ziplime.trading.models.trading_pair import TradingPair


class AssetRepository:

    async def save_equities(self, equities: list[Equity]) -> list[Equity]: ...

    async def save_bonds(self, bonds: list[Bond]) -> list[Bond]: ...

    async def save_bond_events(self, bond_events: list[BondEvent]) -> list[BondEvent]: ...

    async def get_bond_events(self, bonds: list[Bond]) -> dict[int, list[BondEvent]]: ...

    async def get_exchange_bonds_by_symbols(self, symbols: list[AssetSymbol]) -> list[ExchangeAsset]: ...

    async def get_exchange_bond_by_symbol(self, symbol: AssetSymbol) -> ExchangeAsset | None: ...

    async def get_all_bond_listings(self, mic: str | None = None) -> list[ExchangeAsset]: ...

    async def get_bonds_by_isins(self, isins: list[str]) -> list[Bond]: ...
    async def save_symbol_universe(self, symbol_universe: SymbolsUniverse): ...

    async def save_commodities(self, commodities: list[Commodity]) -> list[Commodity]: ...

    async def save_futures_roots(self, futures_roots: list[FuturesRoot]) -> list[FuturesRoot]: ...

    async def save_futures_contracts(self, futures_contracts: list[FuturesContract]) -> list[FuturesContract]: ...

    async def get_futures_roots(self) -> dict[str, FuturesRoot]: ...

    async def get_ordered_contracts(self, root_symbol: str, mic: str | None = None): ...

    async def create_continuous_future(self, root_symbol: str, offset: int, roll_style: str,
                                       adjustment: str | None): ...

    async def get_exchange_futures_contract_by_symbol(self, symbol: AssetSymbol) -> ExchangeAsset | None: ...

    async def get_exchange_futures_contracts_by_root(self, root_symbol: str,
                                                     mic: str | None = None) -> list[ExchangeAsset]: ...

    async def save_asset_routers(self, asset_routers: list[AssetRouter]) -> None: ...

    async def save_currencies(self, currencies: list[Currency]) -> list[Currency]: ...

    async def save_exchanges(self, exchanges: list[ExchangeInfo]) -> None: ...
    async def save_exchange_assets(self, exchange_assets: list[ExchangeAsset]) -> list[ExchangeAsset]: ...
    async def save_dividends(self, dividends: list[DividendPayout]) -> list[DividendPayout]: ...
    async def save_splits(self, splits: list[Split]) -> list[Split]: ...

    async def save_trading_pairs(self, trading_pairs: list[TradingPair]) -> None: ...

    async def get_asset_by_sid(self, sid: int) -> Asset: ...
    async def get_assets_by_ids(self, ids: list[int]) -> list[Asset]: ...
    async def get_equity_by_symbol(self, symbol: str, exchange_name: str) -> Equity | None: ...
    async def get_exchange_equity_by_symbol(self, symbol: AssetSymbol) -> ExchangeAsset | None: ...
    async def get_equities_by_symbols(self, symbols: list[AssetSymbol]) -> list[Equity]: ...
    async def get_exchange_equities_by_symbols(self, symbols: list[AssetSymbol]) -> list[ExchangeAsset]: ...

    async def get_equities_by_isins(self, isins: list[str]) -> list[Equity]: ...

    async def get_symbols_universe(self, name: str, dt: datetime.date) -> SymbolsUniverse | None: ...
    async def lifetimes(self, dates: pd.DatetimeIndex, include_start_date: bool, country_codes: list[str]): ...
    async def asset_lifetimes(self, assets:list[Asset], dates: pd.DatetimeIndex, include_start_date: bool): ...
    async def retrieve_all(self, sids: list[int], default_none: bool = False): ...

    async def get_cash_dividends_with_ex_date(self, assets: list[Asset], date: datetime.date) -> list[DividendPayout]:...
    async def get_splits(self, assets: list[Asset], date: datetime.date) -> list[Split]:...

    async def get_exchange_assets_by_sids(self, sids: list[int]) -> list[ExchangeAsset]: ...
    async def get_all_dividends(self, assets: list[Asset]) -> list[DividendPayout]: ...
    async def get_all_splits(self, assets: list[Asset]) -> list[Split]: ...

    async def get_dividends_by_assets_and_ex_date_between(self, assets: list[Asset],
                                                          ex_date_from: datetime.date,
                                                          ex_date_to: datetime.date) -> list[DividendPayout]: ...
    async def get_splits_by_assets_and_effective_date_between(self, assets: list[Asset],
                                                              effective_date_from: datetime.date,
                                                              effective_date_to: datetime.date) -> list[Split]: ...

    async def preload_corporate_actions(self, assets: list[Asset],
                                        date_from: datetime.date,
                                        date_to: datetime.date) -> None: ...

    @aiocache.cached(cache=Cache.MEMORY)
    async def get_exchange_asset_by_symbol(self, symbol: AssetSymbol, asset_type: AssetType) -> ExchangeAsset | None:
        match asset_type:
            case AssetType.EQUITY:
                return await self.get_exchange_equity_by_symbol(symbol=symbol)
            case AssetType.BOND:
                return await self.get_exchange_bond_by_symbol(symbol=symbol)
            case AssetType.FUTURES_CONTRACT:
                return await self.get_exchange_futures_contract_by_symbol(symbol=symbol)
            case AssetType.CURRENCY:
                return await self.get_exchange_currency_by_symbol(symbol=symbol)
            case AssetType.COMMODITY:
                return await self.get_commodity_by_symbol(symbol=symbol, exchange_name=symbol.mic)
            # case AssetType.OPTIONS_CONTRACT:
            #     return await self.get_options_contract_by_symbol(symbol=symbol, exchange_name=exchange_name)
            case _:
                raise ValueError(f"Unsupported asset type: {asset_type}")

    async def get_futures_contract_by_symbol(self, symbol: str, mic: str | None = None) -> FuturesContract | None: ...

    async def get_currency_by_symbol(self, symbol: str) -> Currency | None: ...
    # async def get_exchange_currency_by_symbol(self, symbol: AssetSymbol) -> ExchangeAsset | None: ...

    async def get_commodity_by_symbol(self, symbol: str, exchange_name:str) -> Commodity | None: ...
    # async def get_options_contract_by_symbol(self, symbol: str, exchange_name:str) -> Commodity | None: ...

    def to_json(self): ...

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Self: ...
